# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.everlasting-garden.com
title: Everlasting Garden - Specialty Herbs and Vegetables
email: cuiyiling@gmail.com
author: Yiling Cui
description: >
  Everlasting Garden is an organic farm growing specialty herbs and vegetables situated in Prunedale, CA
copyright: Copyright &copy; 2020 Everlasting Garden

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
